import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const supabase=createClient('https://clojzlftxumfreyrsugx.supabase.co','sb_publishable_mH67_UIYRx069mQ0PJzpvQ_HIm3eFLZ',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storage:window.localStorage}});
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const num=n=>Number(n||0)||0;
let state=null,user=null,current=null,currentType='';

async function loadState(){const {data:{user:u}}=await supabase.auth.getUser();if(!u)throw new Error('Niet ingelogd');user=u;const {data,error}=await supabase.from('hdm_app_state').select('data').eq('user_id',u.id).limit(1);if(error)throw error;state=data?.[0]?.data||{};for(const k of ['customers','orders','invoices'])if(!Array.isArray(state[k]))state[k]=[];}
async function saveState(){const {error}=await supabase.from('hdm_app_state').update({data:state,updated_at:new Date().toISOString()}).eq('user_id',user.id);if(error)throw error;location.reload();}
function orderFor(c){return (state.orders||[]).filter(o=>o.customerId===c.id).sort((a,b)=>String(b.due||'').localeCompare(String(a.due||'')))[0]||null;}
function openCustomerByName(name){loadState().then(()=>{const c=(state.customers||[]).find(x=>String(x.name||'').trim()===String(name||'').trim());if(!c)return;const o=orderFor(c);current=c;currentType='customer';document.getElementById('detailTitle').textContent='Klant bewerken';document.getElementById('detailFields').innerHTML=`<label>Naam<input id="dName" value="${esc(c.name||'')}"></label><label>Bestelling<input id="dOrder" value="${esc(o?.product||c.product||c.description||'')}"></label><label>Leverdatum<input id="dDue" type="date" value="${esc(String(o?.due||c.due||c.deliveryDate||'').slice(0,10))}"></label>`;document.getElementById('detailModal').hidden=false;});}
function openInvoiceByName(name,number){loadState().then(()=>{let i=(state.invoices||[]).find(x=>number&&String(x.number||'')===String(number));if(!i)i=(state.invoices||[]).find(x=>String(x.customerName||'').trim()===String(name||'').trim());if(!i)return;current=i;currentType='invoice';document.getElementById('detailTitle').textContent='Factuur bewerken';document.getElementById('detailFields').innerHTML=`<label>Factuurnummer<input id="dNumber" value="${esc(i.number||'')}"></label><label>Klant<input id="dCustomer" value="${esc(i.customerName||'')}"></label><label>Datum<input id="dDate" type="date" value="${esc(String(i.date||'').slice(0,10))}"></label><label>Omschrijving<input id="dDescription" value="${esc(i.description||'')}"></label><label>Totaal incl. btw<input id="dTotal" type="number" step="0.01" value="${num(i.total)}"></label><label>Betaald / aanbetaling<input id="dPaid" type="number" step="0.01" value="${num(i.paid)}"></label><label>BTW bedrag<input id="dVat" type="number" step="0.01" value="${num(i.vatAmount)}"></label>`;document.getElementById('detailModal').hidden=false;});}
async function saveDetail(){if(!current)return;const btn=document.getElementById('detailSave');btn.disabled=true;btn.textContent='Opslaan…';try{if(currentType==='customer'){const name=document.getElementById('dName').value.trim(),product=document.getElementById('dOrder').value.trim(),due=document.getElementById('dDue').value;current.name=name;current.product=product;current.description=product;current.due=due;current.deliveryDate=due;current.month=due?due.slice(0,7):current.month;let o=orderFor(current);if(!o){o={id:Date.now().toString(36),customerId:current.id};state.orders.push(o)}o.product=product;o.due=due;o.month=due?due.slice(0,7):'';}else{current.number=document.getElementById('dNumber').value.trim();current.customerName=document.getElementById('dCustomer').value.trim();current.date=document.getElementById('dDate').value;current.month=current.date?current.date.slice(0,7):'';current.description=document.getElementById('dDescription').value.trim();current.total=num(document.getElementById('dTotal').value);current.paid=num(document.getElementById('dPaid').value);current.vatAmount=num(document.getElementById('dVat').value);current.depositRecognized=current.paid>0;}await saveState();}catch(e){alert('Opslaan mislukt: '+e.message);btn.disabled=false;btn.textContent='Wijzigingen opslaan';}}
function enhance(){document.querySelectorAll('#customersBody tr').forEach(tr=>{const td=tr.children[0];if(td&&td.textContent.trim()&&!td.querySelector('button')){const name=td.textContent.trim();td.innerHTML=`<button class="name-link customer-link" type="button">${esc(name)}</button>`;td.querySelector('button').onclick=()=>openCustomerByName(name);}});document.querySelectorAll('#invoicesBody tr').forEach(tr=>{const numCell=tr.children[0],nameCell=tr.children[1];if(nameCell&&nameCell.textContent.trim()&&!nameCell.querySelector('button')){const name=nameCell.textContent.trim(),nr=numCell?.textContent.trim()||'';nameCell.innerHTML=`<button class="name-link invoice-link" type="button">${esc(name)}</button>`;nameCell.querySelector('button').onclick=()=>openInvoiceByName(name,nr);}});}
const obs=new MutationObserver(enhance);obs.observe(document.documentElement,{childList:true,subtree:true});
document.getElementById('detailClose').onclick=()=>document.getElementById('detailModal').hidden=true;document.getElementById('detailCancel').onclick=()=>document.getElementById('detailModal').hidden=true;document.getElementById('detailSave').onclick=saveDetail;document.getElementById('detailModal').addEventListener('click',e=>{if(e.target.id==='detailModal')e.currentTarget.hidden=true});enhance();
